from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pathlib import Path

# ── Theme & Layout Constants ──────────────────────────────────────────────────
# Brand Colors (Dark Mode Tech Theme)
BG_COLOR = RGBColor(0x0B, 0x0E, 0x1A)      # Deep Navy/Black
ACCENT_COLOR = RGBColor(0x3B, 0x82, 0xF6)  # Bright Blue
TEXT_COLOR = RGBColor(0xF3, 0xF4, 0xF6)    # Off-White
TEXT_MUTED = RGBColor(0x9C, 0xA3, 0xAF)    # Grey
CARD_BG = RGBColor(0x1F, 0x29, 0x37)       # Dark Grey/Blue Card

def _bg(slide):
    """Apply standard background."""
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = BG_COLOR

def _title_slide(prs, title: str, subtitle: str):
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    _bg(slide)
    
    # Title
    t = slide.shapes.title
    t.text = title
    t.text_frame.paragraphs[0].font.color.rgb = TEXT_COLOR
    t.text_frame.paragraphs[0].font.size = Pt(44)
    t.text_frame.paragraphs[0].font.bold = True
    
    # Subtitle
    if slide.placeholders.count > 1:
        s = slide.placeholders[1]
        s.text = subtitle
        s.text_frame.paragraphs[0].font.color.rgb = ACCENT_COLOR
        s.text_frame.paragraphs[0].font.size = Pt(24)

def _data_story_slide(prs, title: str, bullets: list[str], chart_path: str):
    """
    Creates a slide with a chart on the right and narrative bullets on the left.
    """
    slide = prs.slides.add_slide(prs.slide_layouts[6]) # Blank layout
    _bg(slide)

    # 1. Header
    left = Inches(0.5)
    top = Inches(0.4)
    width = Inches(9)
    height = Inches(1.0)
    
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    p.text = title
    p.font.bold = True
    p.font.size = Pt(28)
    p.font.color.rgb = TEXT_COLOR
    
    # 2. Add Chart (Right Side)
    # Target area: Left ~6.5", Top ~1.8", Width ~6.5", Height ~5.0"
    chart_placed = False
    if chart_path and Path(chart_path).exists():
        try:
            # Fixed dimensions
            cx, cy = Inches(6.0), Inches(1.6)
            cw, ch = Inches(7.0), Inches(5.0)
            slide.shapes.add_picture(chart_path, cx, cy, cw, ch)
            chart_placed = True
        except Exception:
            pass
            
    # 3. Add Narrative Bullets (Left Side)
    # If chart placed, use left column. If not, use full width.
    bx, by = Inches(0.5), Inches(1.6)
    bw = Inches(5.0) if chart_placed else Inches(9.0)
    bh = Inches(5.0)
    
    bBox = slide.shapes.add_textbox(bx, by, bw, bh)
    tf = bBox.text_frame
    tf.word_wrap = True
    
    for bullet in bullets:
        p = tf.add_paragraph()
        p.text = bullet
        p.font.size = Pt(18)
        p.font.color.rgb = TEXT_COLOR
        p.space_after = Pt(14)
        p.level = 0
        
        # Add a custom bullet character if possible, or just standard
        # For now, standard dash is fine. 
        # To make it "McKinsey style", we often use bold lead-ins manually if provided.

def _summary_slide(prs, title: str, content: list[str]):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _bg(slide)
    
    # Header
    left = Inches(0.5); top = Inches(0.5); width = Inches(9); height = Inches(1)
    t = slide.shapes.add_textbox(left, top, width, height).text_frame.paragraphs[0]
    t.text = title
    t.font.bold = True; t.font.size = Pt(32); t.font.color.rgb = ACCENT_COLOR
    
    # Content
    left = Inches(1.0); top = Inches(1.8); width = Inches(8.5); height = Inches(5)
    tx = slide.shapes.add_textbox(left, top, width, height)
    for line in content:
        p = tx.text_frame.add_paragraph()
        p.text = line
        p.font.size = Pt(22)
        p.font.color.rgb = TEXT_COLOR
        p.space_after = Pt(20)

def export_pptx(result: dict, output_path: Path, charts_dir: Path = None):
    """
    Generate a curated, narrative-driven presentation.
    Uses the structure defined by the LLM in 'presentation_payload'.
    """
    prs = Presentation()
    
    # Dimensions: 16:9
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)
    
    # Get payload
    payload = result.get("presentation", {})
    slides = payload.get("slides", [])
    
    # Fallback if empty (shouldn't happen with new prompt)
    if not slides:
        _title_slide(prs, "Analysis Report", "Generated by Analyst Agent")
        
    # Build slides based on LLM 'type'
    success_count = 0
    for i, slide_data in enumerate(slides):
        try:
            stype = slide_data.get("type", "generic")
            title = slide_data.get("title", f"Slide {i+1}")
            content = slide_data.get("content", [])
            
            if isinstance(content, str):
                content = [content]
                
            if stype == "title":
                subtitle = slide_data.get("subtitle", "")
                _title_slide(prs, title, subtitle)
                
            elif stype in ["summary", "recommendations"]:
                _summary_slide(prs, title, content)
                
            elif stype == "chart":
                # Resolve chart path
                # The LLM returns the *name* or *relative path* or *full path*
                c_ref = slide_data.get("chart_reference")
                real_path = None
                if c_ref and charts_dir:
                    # Try exact match
                    p = charts_dir / Path(c_ref).name
                    if p.exists():
                        real_path = str(p)
                    else:
                        # Fuzzy match?
                        try:
                            # If chart_reference is just a step number 'Step 3', find first chart for that step
                            pass
                        except Exception:
                            pass
                
                _data_story_slide(prs, title, content, real_path)
                
            else:
                # Generic fallback
                _summary_slide(prs, title, content)
            
            success_count += 1
            
        except Exception as e:
            print(f"Failed to generate slide {i}: {e}")
            # Continue to next slide instead of crashing
            continue
            
    if success_count == 0:
        # If all failed or none existed, add a fallback slide
        _title_slide(prs, "Analysis Complete", "See full report in dashboard.")
            
    prs.save(str(output_path))
    return str(output_path)
